name: LMGTFY
author: Nikl
main: me.nikl.lmgtfy.Main
version: 1.0.1
website: nikl.me

commands:
  lmgtfy:
    description: let me google that for you
    usage: /lmgtfy <search>
    aliases: [lmg]
  google:
    description: google stuff...
    usage: /google <search>
    aliases: []

permissions:
  lmgtfy.*:
    description: Gives all permissions
    children:
      lmgtfy.use: true
  lmgtfy.use:
    description: Allows to create lmgtfy links
    default: true